<?php defined('SYSPATH') or die('No direct access allowed.');

/**
 * @author K Anderson
 * @license LGPL
 * @package FreePBX3
 * @subpackage NetListManager
 */

class NetListManager_Plugin extends FreePbx_Plugin
{
    public function delete() {
        $base = Event::$data;

        if (!$base)
            return FALSE;

        // Stop the delete of system net lists
        if (!empty($base['system_list'])) {
            throw new FreePbx_Validation_Exception($base['name'] . ' is generated by FreeSwitch and can not be removed!', 2);

        // if we should be able to remove this also delete all the items
        } else if ($base->hasRelation('NetListItem')) {
            foreach($base->NetListItem as $netListItem) {
                $netListItem->delete();
            }

            /**
             * TODO: If something was using this list inform it that the list is gone
             */
        }
    }

}