<?php if(!defined('IN_RAINTPL')){exit('Hacker attempt');}?><!-- advanced_subheader | generated by RainTPL v 1.7.5 | www.RainTPL.com -->
<table align='center' width='90%'>
<tr>
<td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=settings'><?=_('Settings')?></a></h4></td>
<td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=oui_manager'><?=_('OUI Manager')?></a></h4></td>
<td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=poce'><?=_('Product Options/Configuration Editor')?></a></h4></td>
</tr>
<tr>
    <td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=iedl'><?=_('Import/Export Devices My Devices List')?></a></h4></td>
<td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=manual_upload'><?=_('Manual Endpoint Modules Upload')?></a></h4></td>
<td align='center'><h4><a href='<?php echo $var["web_vars"];?>&display=epm_advanced&subpage=sh_manager'><?=_('Show/Hide Brands/Models')?></a></h4></td>
</tr>
</table>
<hr width='90%'>

<!--/ advanced_subheader -->
