<?php if(!defined('IN_RAINTPL')){exit('Hacker attempt');}?><!-- global_footer | generated by RainTPL v 1.7.5 | www.RainTPL.com -->
<hr>
<h6 align='center'>The Endpoint Configuration Manager is currently maintained by <a target="_blank" href=http://www.andrewsnagy.com/>Andrew Nagy</a>
<br/><?=_("The Endpoint Configuration Manager was originally written by")?> <a target="_blank" href=http://www.mymcs.us>Ed Macri</a>, <a target="_blank" href=http://www.cohutta.com> John Mullinix.</a> and <a target="_blank" href=http://www.colsolgrp.com>Tony Shiffer</a>
<br/>Endpoint Configuration Manager uses code from the MPL licensed project Provisioner.net at <a href="http://https://www.assembla.com/code/provisioner/git/nodes?rev=master">https://www.assembla.com/code/provisioner/git/nodes?rev=master</a> co-written by Darren Schreiber &amp Andrew Nagy
<br> <?=_("The project is maintained at")?> 
<a target="_blank" href="http://projects.colsolgrp.net/projects/show/endpointman"> CSG Software Projects.</a>
</body>
</html> 

<!--/ global_footer -->
