<?php



/**
 * @file
 * Functions for the interface to the call monitor recordings
 */

/**
  * Class for settings
  */
class phonesettings {

  /*
   * rank (for prioritizing modules)
   */
  function rank() {

    $rank = 10;
    return $rank;
  }

  /*
   * init
   */
  function init() {
  }
 
  /*
   * Adds menu item to nav menu
   *
   * @param $args
   *   Common arguments
   */
  function navMenu($args) {

	$ret = "";
	$exten = $_SESSION['ari_user']['extension'];

	$sql = "SELECT * FROM endpointman_global_vars WHERE var_name = 'enable_ari'";
    $results = $_SESSION['dbh_asterisk']->getAll($sql, DB_FETCHMODE_ASSOC);

	// and we are not logged in as admin
	if (($exten!=$ARI_ADMIN_USERNAME) AND ($results[0]['value'])) {
		$ret .= "<p><small><small><a href='" . $_SESSION['ARI_ROOT'] . "?m=phonesettings&f=display'>" . _("Phone Settings") . "</a></small></small></p><br>";
	}

    return $ret;
  }

  /*
   * Acts on the user settings
   *
   * @param $args
   *   Common arguments
   * @param $a
   *   action
   */
  function action($args) {	
	global $endpoint, $global_cfg;

	$doc_root =	$_SERVER["DOCUMENT_ROOT"] ."/admin/modules/endpointman/";
	require($doc_root . "includes/functions.inc");
	
	$endpoint = new endpointmanager();
	
	$sql = "SELECT id FROM endpointman_mac_list WHERE ext = '".$_SESSION['ari_user']['extension']."' ";
	$results = mysql_query($sql);
	$row = mysql_fetch_assoc($results);
	

	$id = $row['id'];

	$row = $endpoint->get_phone_info($id);
	
	$cfg_data = unserialize($row['cfg_data']);
	
	
	if($row['custom_cfg_template'] > 0) {
		$row['custom_cfg_data'] = $row['template_data']['custom_cfg_data'];
	}
	$custom_cfg_data2 = unserialize($row['custom_cfg_data']);
	
	$count = count($cfg_data);
	for($i=0;$i<=$count;$i++) {
		$temping = str_replace('$','',$cfg_data[$i]['variable']);
		if((isset($_REQUEST[$temping])) AND (isset($custom_cfg_data2[$temping]['ari'])) AND ($custom_cfg_data2[$temping]['ari'] == 1)) {
			$custom_cfg_data[$temping]['value'] = $_REQUEST[$temping];
		}
	}
		
	$custom_cfg_data = serialize($custom_cfg_data);
	
	$sql = "UPDATE endpointman_mac_list SET user_cfg_data = '".$custom_cfg_data."' WHERE id = ". $id;
	mysql_query($sql);
	
	require(PHONE_MODULES_PATH.$row['directory'].'/'.$row['cfg_dir'].'/functions.inc');

	$phone_config = new $row['cfg_dir']();
	$phone_config->generate_config($id);
	
	$m = "phonesettings";
	
	$ret .= "
      <head>
        <script>
        <!--
          window.location = \"" . $_SESSION['ARI_ROOT'] . "?m=" . $m . "\"
        // -->
        </script>
    </head>";
	
    return $ret;
  }

  function reloadSettings($exten) {

  }

  /*
   * Displays stats page
   *
   * @param $args
   *   Common arguments
   */
  function display($args) {
	if (!isset($_SESSION['dbh_asterisk'])) {
		die('No Database?');
    }
	
	$doc_root =	$_SERVER["DOCUMENT_ROOT"] ."/admin/modules/endpointman/";
	require($doc_root . "includes/functions.inc");
	
	$endpoint = new endpointmanager();
	
	$sql = "SELECT id FROM endpointman_mac_list WHERE ext = '".$_SESSION['ari_user']['extension']."' ";
	$results = mysql_query($sql);
	$row = mysql_fetch_assoc($results);
	
	global $global_cfg;

	$row = $endpoint->get_phone_info($row['id']);
	

	

	if(!$endpoint->sync_product($row['product_id'])) {
		die("unable to sync local template files". $custom);
	}
	
	//Get default template config data from the database for this product
	$sql = "SELECT cfg_data FROM endpointman_product_list WHERE id=". $row['product_id'];
	$result=mysql_query($sql);
	$product_row=mysql_fetch_array($result);		
	
	//inset it into our usable row
	$row['cfg_data'] = $product_row['cfg_data'];

	$brand_name = $row['directory'];
	$model_name = $row['cfg_dir'];

		
	//Start the display of the html file in the product folder
	
	$template .=  '<h3>Hello '. $row['description'] . ', You are currently editing phone settings for extension '.$row['ext'].'</h3><br />';
	
	if($row['custom_cfg_template'] > 0) {
		$row['custom_cfg_data'] = $row['template_data']['custom_cfg_data'];
	} 

	$out = $endpoint->generate_gui_html($row['cfg_data'],$row['custom_cfg_data'],FALSE,$row['user_cfg_data']);
	
	$out[0]['data'] = array_values($out[0]['data']);
	
	$out[0]['title'] = "Your Phone Settings";
	
	$tpl = new RainTPL( LOCAL_PATH.'templates' );
	
	$tpl->assign("in_ari", 1);
	$tpl->assign("template_editor", $out);
	$tpl->assign("hidden_id", $row['id']);
	$tpl->assign("hidden_custom", $custom);
	$template .= $tpl->draw( 'template_editor', TRUE );
	

	$m = "phonesettings";
	$ret .= "<form class='phonesettings' name='ari_settings' action='' method='GET'>
	<input type=hidden name=m value=" . $m . ">
	<input type=hidden name=f value='action'>
	<input type=hidden name=a value='update'>
	<br>
	" . $template . "
	<br>
	<input name='submit' type='submit' value='Save & Reboot'>
	</form>";
	return($ret);
  }
} // class

?>
